language: c++

dist: trusty
sudo: required
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - kubuntu-backports
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - g++-6
            - cmake
            - cmake-data
            - libbullet-dev
            - freeglut3-dev
            - libglu1-mesa-dev
            - libx11-dev
            - libxxf86vm-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install glfw;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis_retry git clone --depth 1 -b 3.2.1 https://github.com/glfw/glfw.git ;
      (cd glfw && mkdir build && cd build cmake -D GLFW_INSTALL=ON -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_DOCS=OFF -D GLFW_BUILD_TESTS=OFF && make install)
    fi
  
script:
  - mkdir build && cd build && cmake .. && make -j2
  