version: 1.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2015
environment:
  GLFW_URL: https://github.com/glfw/glfw.git
  GLFW_ROOT: c:\projects\dep\glfw
  OUT_ROOT: c:\projects\output
install:
- cmd: >-
    mkdir c:\projects\dep\

    git clone --depth=1 -b 3.2.1 %GLFW_URL%


    if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET CMAKE_GENERATOR="Visual Studio 14 2015 Win64" )

    if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( SET CMAKE_GENERATOR="Visual Studio 15 2017 Win64" )


    cd glfw && mkdir build && cd build

    cmake -G %CMAKE_GENERATOR% -D GLFW_INSTALL=ON -D GLFW_BUILD_EXAMPLES=OFF -D GLFW_BUILD_DOCS=OFF -D GLFW_BUILD_TESTS=OFF -D CMAKE_INSTALL_PREFIX=%GLFW_ROOT% ..

    cmake --build . --config Release --target ALL_BUILD

    cmake --build . --config Release --target INSTALL

    cd %APPVEYOR_BUILD_FOLDER%
build_script:
- cmd: >-
    mkdir build && cd build

    cmake -G %CMAKE_GENERATOR% -D FindGLFW_Test_GLFW_ROOT=%GLFW_ROOT% -D CMAKE_INSTALL_PREFIX=..\output ..

    cmake --build . --config Release --target ALL_BUILD

    cmake --build . --config Release --target INSTALL
artifacts:
- path: .\output